### PR TITLE
Added random password generator using python

### PR DESCRIPTION
**Pull request by anushkamandal25**
Hello! Pls check the pr @techyminati

### CODE REVIEW

**Comment by anushkamandal25** [comment]
kindly check my pr @techyminati

**Comment by techyminati** [comment]
sure, please do star this repo and follow me if you can :P

**Comment by Meghthedev** [comment]
> sure, please do star this repo and follow me if you can :P

@techyminati is this not duplicate?

**Comment by techyminati** [comment]
I try my best to filter out duplicates and spam most of time :), there is possibility i might have skipped few of them, I'm not a robot :).

**Comment by Meghthedev** [comment]
> I try my best to filter out duplicates and spam most of time :), there is possibility i might have skipped few of them, I'm not a robot :).

@techyminati or are you a robot? Hmmmm sus😁

**Pull request merged**
